### ISSUE TITLE
Component 'PrintDialogExtension' cannot be activated if baselayer with child elements is default baselayer

### ISSUE THREAD

**Issue by oliverkosky** [conterra/mapapps-agsprinting-enhanced#3]
# Reproduction
* Create a baselayer with child elements (see app attached)
* This layer must be active by default
* Start app

# Expected
* App starts without any problems

# Actual behaviour
* App starts, but the dn_agsprintingenhanced bundle cannot be activated (see console.log)
[conole.log](https://github.com/conterra/mapapps-agsprinting-enhanced/files/1457352/conole.log)
[crn11806.zip](https://github.com/conterra/mapapps-agsprinting-enhanced/files/1457353/crn11806.zip)

**Comment by JoergArnold** [comment]
Thank you for this fix.
Now it works fine in our app for baselayer with child elements.
Would you publish please a new release 1.0.x of this fix?
bye,
JoergArnold

**Comment by matthiasstein** [comment]
Of course I've created a new release: https://github.com/conterra/mapapps-agsprinting-enhanced/releases/tag/1.0.1
