### ISSUE TITLE
Error message if layoutTemplatesInfoTaskName is not defined

### ISSUE THREAD

**Issue by GiuliaMischitelli** [conterra/mapapps-agsprinting-enhanced#8]
The Property "layoutTemplatesInfoTaskName" of the component PrintController is necessary for the good functioning of the bundle.
If this property is not defined in the configuration, the frame for printing wouldn't be shown, but no error message appears.

**Comment by matthiasstein** [comment]
The property _layoutTemplatesInfoTaskName_ only needs to be configured if the interface name is different from the default name "Get Layout Templates Info Task". Have a look at the documentation: https://developernetwork.conterra.de/en/documentation/mapapps/39/developers-documentation/ags-printing
